dotfiles_dir = ".dotfiles"

[settings]
posthooks = [
    "nvim --headless +PlugInstall +PlugClean! +quitall",
    "sway reload",
    "fc-cache"
]

[settings.dots]
fonts = { source = "fonts", target = ".local/share/fonts" }

sway = { source = "sway", target = ".config/sway" }
waybar = { source = "waybar", target = ".config/waybar" }
neovim = { source = "neovim", target = ".config/nvim" }
wezterm = { source = "wezterm", target = ".config/wezterm" }
gitconfig = { source = "git/gitconfig", target = ".gitconfig" }

fish_config = { source = "fish/config.fish", target = ".config/fish/config.fish" }
fish_confd = { source = "fish/conf.d", target = ".config/fish/conf.d" }
oh_my_fish = { source = "fish/omf", target = ".config/omf" }
