# set-option -g default-terminal "xterm-256color"
set-option -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

set -s escape-time 0

unbind C-b
set-option -g prefix `
bind ` send-prefix

bind r source-file ~/.tmux.conf
set -g base-index 1

set -g mouse off

bind-key -r f run-shell "tmux neww ~/bin/tmux-sessionizer"
bind-key -r A run-shell "~/bin/tmux-sessionizer ~/qsic/Code/qsic-api-django"
bind-key -r Q run-shell "~/bin/tmux-sessionizer ~/qsic/Code/qbit"
bind-key -r S run-shell "~/bin/tmux-sessionizer ~/qsic/Support"
bind-key -r P run-shell "~/bin/tmux-sessionizer ~/personal/Code/"
bind-key -r T run-shell "~/bin/tmux-sessionizer ~/qsic/Code/qsic-infrastructure"

bind-key -r \\ last-window
bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fabioluciano/tmux-tokyo-night'

set -g @tokyo-night-tmux_window_id_style fsquare
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare 


run '~/.tmux/plugins/tpm/tpm'
